spring.application.name=login

# Database configuration (Oracle)
spring.datasource.url=jdbc:oracle:thin:@localhost:1521:xe
spring.datasource.username=CRUD
spring.datasource.password=crud123
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

# If you want the app to create/update tables automatically set below (dev only)
spring.jpa.hibernate.ddl-auto=none

# Do not create default users in your database by default. Set to true to
# let the app insert two demo users (user/password and admin/admin).
spring.jpa.show-sql=true


