spring.application.name=login
spring.data.jpa.repositories.enabled=false

app.datasource.local.url=jdbc:oracle:thin:@localhost:1521:xe
app.datasource.local.username=CRUD
app.datasource.local.password=crud123
app.datasource.local.driver-class-name=oracle.jdbc.OracleDriver

adm.datasource.url=jdbc:oracle:thin:@10.26.1.81:1521:ORCL
adm.datasource.username=radmdb
adm.datasource.password=radmdb2022
adm.datasource.driver-class-name=oracle.jdbc.OracleDriver

it.datasource.url=jdbc:oracle:thin:@10.26.1.81:1521:ORCL
it.datasource.username=rsitdb
it.datasource.password=rsitdb2022
it.datasource.driver-class-name=oracle.jdbc.OracleDriver

server.port=8082
spring.jpa.hibernate.ddl-auto=none
spring.thymeleaf.cache=false
spring.jpa.show-sql=true
spring.jpa.open-in-view=false




